import { library, config } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import {
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowUpRightFromSquare,
  faArrowsAltV,
  faAt,
  faBackspace,
  faBars,
  faBriefcase,
  faCalendar,
  faCamera,
  faCaretDown,
  faCaretRight,
  faCheck,
  faCheckCircle,
  faCheckSquare,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircle,
  faCircleUser,
  faCloudUploadAlt,
  faCode,
  faCompress,
  faEarthAsia,
  faEdit,
  faExclamation,
  faExclamationTriangle,
  faEyeDropper,
  faFilter,
  faFilterCircleXmark,
  faImage,
  faInfoCircle,
  faKeyboard,
  faLayerGroup,
  faMagnifyingGlass,
  faMapMarkerAlt,
  faMinus,
  faMinusSquare,
  faMoon,
  faPalette,
  faPaperclip,
  faPause,
  faPlay,
  faPlus,
  faReply,
  faSliders,
  faSquare,
  faStar,
  faStarHalf,
  faStepBackward,
  faStepForward,
  faSun,
  faSync,
  faTimes,
  faTimesCircle,
  faVolumeHigh,
  faVolumeLow,
  faVolumeOff,
  faXmark,
} from '@fortawesome/free-solid-svg-icons';
import {
  faCircle as farCircle,
  faDotCircle,
  faImages,
  faSquare as farSquare,
  faStar as farStar,
} from '@fortawesome/free-regular-svg-icons';
import {
  faDribbble,
  faGithub,
  faInstagram,
  faLinkedin,
} from '@fortawesome/free-brands-svg-icons';

// FontAwesome auto-injects its CSS at runtime (flash of oversized icons); nuxt.config ships its stylesheet instead.
config.autoAddCss = false;

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('font-awesome-icon', FontAwesomeIcon);
  // Most of these are not named in app code; they back Vuetify's fa-svg chrome (vuetify/iconsets/fa), which resolves icons by string and renders blank if one is unregistered.
  library.add(
    faArrowDown,
    faArrowLeft,
    faArrowRight,
    faArrowUp,
    faArrowUpRightFromSquare,
    faArrowsAltV,
    faAt,
    faBackspace,
    faBars,
    faBriefcase,
    faCalendar,
    faCamera,
    faCaretDown,
    faCaretRight,
    faCheck,
    faCheckCircle,
    faCheckSquare,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faChevronUp,
    faCircle,
    faCircleUser,
    faCloudUploadAlt,
    faCode,
    faCompress,
    faEarthAsia,
    faEdit,
    faExclamation,
    faExclamationTriangle,
    faEyeDropper,
    faFilter,
    faFilterCircleXmark,
    faImage,
    faInfoCircle,
    faKeyboard,
    faLayerGroup,
    faMagnifyingGlass,
    faMapMarkerAlt,
    faMinus,
    faMinusSquare,
    faMoon,
    faPalette,
    faPaperclip,
    faPause,
    faPlay,
    faPlus,
    faReply,
    faSliders,
    faSquare,
    faStar,
    faStarHalf,
    faStepBackward,
    faStepForward,
    faSun,
    faSync,
    faTimes,
    faTimesCircle,
    faVolumeHigh,
    faVolumeLow,
    faVolumeOff,
    faXmark,
    farCircle,
    faDotCircle,
    faImages,
    farSquare,
    farStar,
    faDribbble,
    faGithub,
    faInstagram,
    faLinkedin,
  );
});
